from .mock_aegis import C, get_agent_stats, print_agent_banner, log_thought
from .tools import (
    lookup_balance,
    get_transaction_history,
    send_notification,
    scan_transactions,
    flag_account,
    verify_identity,
    check_credit_score,
    process_application,
    access_credit_card,
    access_ssn,
    access_phone,
    delete_records,
    connect_external,
    get_customer_preferences,
    send_promo_email,
    generate_report,
    export_customer_list,
)

# All 17 tools in one list — agents get the full toolkit, Aegis policy is the only gatekeeper
ALL_TOOLS = [
    lookup_balance,
    get_transaction_history,
    send_notification,
    scan_transactions,
    flag_account,
    verify_identity,
    check_credit_score,
    process_application,
    access_credit_card,
    access_ssn,
    access_phone,
    delete_records,
    connect_external,
    get_customer_preferences,
    send_promo_email,
    generate_report,
    export_customer_list,
]
